# Generated by Django 4.2.7 on 2025-10-28 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DebateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('win_probability', models.IntegerField()),
                ('probability_justification', models.TextField()),
                ('positive_factors', models.JSONField(default=list)),
                ('negative_factors', models.JSONField(default=list)),
                ('suggested_tasks', models.JSONField(default=list)),
                ('deep_dive_analysis', models.TextField(blank=True, null=True)),
                ('courtroom_scenario', models.TextField(blank=True, null=True)),
                ('cross_examination_questions', models.JSONField(default=list)),
                ('closing_argument_lead', models.TextField(blank=True, null=True)),
                ('closing_argument_defender', models.TextField(blank=True, null=True)),
                ('client_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(max_length=100)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_facts', models.JSONField(default=list)),
                ('legal_issues', models.JSONField(default=list)),
                ('applicable_laws', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('statute_of_limitations_status', models.CharField(default='OK', max_length=20)),
                ('statute_of_limitations_summary', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.TextField()),
                ('likelihood', models.CharField(max_length=10)),
                ('mitigation', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(default='event', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('case_details', models.TextField()),
                ('court_stage', models.CharField(max_length=100)),
                ('client_role', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('folder', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ManyToManyField(blank=True, related_name='cases', to='cases.billingentry')),
                ('debate_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.debateresult')),
                ('evidence', models.ManyToManyField(blank=True, related_name='cases', to='cases.evidenceitem')),
                ('files', models.ManyToManyField(blank=True, related_name='cases', to='cases.casefile')),
                ('knowledge_base', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.knowledgebasesection')),
                ('notes', models.ManyToManyField(blank=True, related_name='cases', to='cases.note')),
                ('participants', models.ManyToManyField(blank=True, related_name='cases', to='cases.caseparticipant')),
                ('risk_matrix', models.ManyToManyField(blank=True, related_name='cases', to='cases.riskmatrixentry')),
                ('tasks', models.ManyToManyField(blank=True, related_name='cases', to='cases.task')),
                ('timeline', models.ManyToManyField(blank=True, related_name='cases', to='cases.timelineevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
